"""Static contract for the privileged Thor nvpmodel sweep wrapper."""
from pathlib import Path
import subprocess


def test_thor_sweep_help_and_safety_contract():
    root = Path(__file__).resolve().parents[1]
    script = root / 'scripts/profile/sweep-thor.sh'
    result = subprocess.run(['bash', str(script), '--help'], capture_output=True,
                            text=True, timeout=10)
    assert result.returncode == 0, result.stderr
    assert 'modes 0-3' in result.stdout
    source = script.read_text()
    assert 'original_mode=' in source
    assert 'trap restore_mode EXIT' in source
    assert 'sudo nvpmodel -m "$mode"' in source
    assert 'sudo nvpmodel -m "$original_mode"' in source
    assert '--power-perc 1.0' in source
    assert 'local num_views=2' in source
    assert '--num-views "$num_views"' in source
    assert 'No policy profiles were produced' in source
    assert '${OPENPI_EXECUTIONS:-graph}' in source
    assert '${FLASHRT_EXECUTIONS:-graph}' in source
    assert 'run_profile "$mode" flash_rt "$execution"' in source
    assert 'all_policy_profile.csv' not in source  # generated by filename prefix
    assert 'f"all_{filename}"' in source
